/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/BaseLayout/index.vue";
import MenuLayout from "@/layouts/MenuLayout/index.vue";
import BlankLayout from "@/layouts/BlankLayout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  menu: MenuLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  home: () => import("@/views/Home/index.vue"),
  ucenter: () => import("@/views/UCenter/index.vue"),
  403: () => import("@/views/_blank/403/index.vue"),
  404: () => import("@/views/_blank/404/index.vue"),
  login: () => import("@/views/_blank/Login/index.vue"),
  redirect: () => import("@/views/_blank/Redirect/index.vue"),
  register: () => import("@/views/_blank/Register/index.vue"),
  theme: () => import("@/views/_blank/Theme/index.vue"),
  system_menu: () => import("@/views/system/Menu/index.vue"),
  system_role: () => import("@/views/system/Role/index.vue"),
  system_statistic: () => import("@/views/system/Statistic/index.vue"),
  system_user: () => import("@/views/system/User/index.vue"),
  template_chart: () => import("@/views/template/Chart/index.vue"),
  template_dashboard: () => import("@/views/template/Dashboard/index.vue"),
  template_element_calendar: () => import("@/views/template/element/Calendar/index.vue"),
  template_element_carousel: () => import("@/views/template/element/Carousel/index.vue"),
  template_element_form: () => import("@/views/template/element/Form/index.vue"),
  template_element_statistic: () => import("@/views/template/element/Statistic/index.vue"),
  template_element_steps: () => import("@/views/template/element/Steps/index.vue"),
  template_element_tableedit: () => import("@/views/template/element/TableEdit/index.vue"),
  template_element_tabs: () => import("@/views/template/element/Tabs/index.vue"),
  template_element_tour: () => import("@/views/template/element/Tour/index.vue"),
  template_element_upload: () => import("@/views/template/element/Upload/index.vue"),
  template_element_watermark: () => import("@/views/template/element/Watermark/index.vue"),
  template_pages_editor: () => import("@/views/template/pages/Editor/index.vue"),
  template_pages_markdown: () => import("@/views/template/pages/Markdown/index.vue"),
  template_pages_resetpwd: () => import("@/views/template/pages/ResetPwd/index.vue"),
  template_pages_ucenter: () => import("@/views/template/pages/UCenter/index.vue"),
  template_system_menu: () => import("@/views/template/system/Menu/index.vue"),
  template_system_role: () => import("@/views/template/system/Role/index.vue"),
  template_system_user: () => import("@/views/template/system/User/index.vue"),
  template_table_basetable: () => import("@/views/template/table/BaseTable/index.vue"),
  template_table_export: () => import("@/views/template/table/Export/index.vue"),
  template_table_import: () => import("@/views/template/table/Import/index.vue"),
  template_table_tableeditor: () => import("@/views/template/table/TableEditor/index.vue"),
  template_table_templatetable: () => import("@/views/template/table/TemplateTable/index.vue"),
};
