/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403'
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页'
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    meta: {
      title: 'login'
    }
  },
  {
    name: 'redirect',
    path: '/redirect',
    component: 'layout.blank$view.redirect',
    meta: {
      title: 'redirect'
    }
  },
  {
    name: 'register',
    path: '/register',
    component: 'layout.blank$view.register',
    meta: {
      title: 'register',
      icon: 'register'
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.menu',
    meta: {
      title: 'system'
    },
    children: [
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role'
        }
      },
      {
        name: 'system_statistic',
        path: '/system/statistic',
        component: 'view.system_statistic',
        meta: {
          title: 'system_statistic'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user'
        }
      }
    ]
  },
  {
    name: 'template',
    path: '/template',
    component: 'layout.menu',
    meta: {
      title: 'template'
    },
    children: [
      {
        name: 'template_chart',
        path: '/template/chart',
        component: 'view.template_chart',
        meta: {
          title: 'template_chart'
        }
      },
      {
        name: 'template_dashboard',
        path: '/template/dashboard',
        component: 'view.template_dashboard',
        meta: {
          title: 'template_dashboard'
        }
      },
      {
        name: 'template_element',
        path: '/template/element',
        meta: {
          title: 'template_element'
        },
        children: [
          {
            name: 'template_element_calendar',
            path: '/template/element/calendar',
            component: 'view.template_element_calendar',
            meta: {
              title: 'template_element_calendar'
            }
          },
          {
            name: 'template_element_carousel',
            path: '/template/element/carousel',
            component: 'view.template_element_carousel',
            meta: {
              title: 'template_element_carousel'
            }
          },
          {
            name: 'template_element_form',
            path: '/template/element/form',
            component: 'view.template_element_form',
            meta: {
              title: 'template_element_form'
            }
          },
          {
            name: 'template_element_statistic',
            path: '/template/element/statistic',
            component: 'view.template_element_statistic',
            meta: {
              title: 'template_element_statistic'
            }
          },
          {
            name: 'template_element_steps',
            path: '/template/element/steps',
            component: 'view.template_element_steps',
            meta: {
              title: 'template_element_steps'
            }
          },
          {
            name: 'template_element_tableedit',
            path: '/template/element/tableedit',
            component: 'view.template_element_tableedit',
            meta: {
              title: 'template_element_tableedit'
            }
          },
          {
            name: 'template_element_tabs',
            path: '/template/element/tabs',
            component: 'view.template_element_tabs',
            meta: {
              title: 'template_element_tabs'
            }
          },
          {
            name: 'template_element_tour',
            path: '/template/element/tour',
            component: 'view.template_element_tour',
            meta: {
              title: 'template_element_tour'
            }
          },
          {
            name: 'template_element_upload',
            path: '/template/element/upload',
            component: 'view.template_element_upload',
            meta: {
              title: 'template_element_upload'
            }
          },
          {
            name: 'template_element_watermark',
            path: '/template/element/watermark',
            component: 'view.template_element_watermark',
            meta: {
              title: 'template_element_watermark'
            }
          }
        ]
      },
      {
        name: 'template_pages',
        path: '/template/pages',
        meta: {
          title: 'template_pages'
        },
        children: [
          {
            name: 'template_pages_editor',
            path: '/template/pages/editor',
            component: 'view.template_pages_editor',
            meta: {
              title: 'template_pages_editor'
            }
          },
          {
            name: 'template_pages_markdown',
            path: '/template/pages/markdown',
            component: 'view.template_pages_markdown',
            meta: {
              title: 'template_pages_markdown'
            }
          },
          {
            name: 'template_pages_resetpwd',
            path: '/template/pages/resetpwd',
            component: 'view.template_pages_resetpwd',
            meta: {
              title: 'template_pages_resetpwd'
            }
          },
          {
            name: 'template_pages_ucenter',
            path: '/template/pages/ucenter',
            component: 'view.template_pages_ucenter',
            meta: {
              title: 'template_pages_ucenter'
            }
          }
        ]
      },
      {
        name: 'template_system',
        path: '/template/system',
        meta: {
          title: 'template_system'
        },
        children: [
          {
            name: 'template_system_menu',
            path: '/template/system/menu',
            component: 'view.template_system_menu',
            meta: {
              title: 'template_system_menu'
            }
          },
          {
            name: 'template_system_role',
            path: '/template/system/role',
            component: 'view.template_system_role',
            meta: {
              title: 'template_system_role'
            }
          },
          {
            name: 'template_system_user',
            path: '/template/system/user',
            component: 'view.template_system_user',
            meta: {
              title: 'template_system_user'
            }
          }
        ]
      },
      {
        name: 'template_table',
        path: '/template/table',
        meta: {
          title: 'template_table'
        },
        children: [
          {
            name: 'template_table_basetable',
            path: '/template/table/basetable',
            component: 'view.template_table_basetable',
            meta: {
              title: 'template_table_basetable'
            }
          },
          {
            name: 'template_table_export',
            path: '/template/table/export',
            component: 'view.template_table_export',
            meta: {
              title: 'template_table_export'
            }
          },
          {
            name: 'template_table_import',
            path: '/template/table/import',
            component: 'view.template_table_import',
            meta: {
              title: 'template_table_import'
            }
          },
          {
            name: 'template_table_tableeditor',
            path: '/template/table/tableeditor',
            component: 'view.template_table_tableeditor',
            meta: {
              title: 'template_table_tableeditor'
            }
          },
          {
            name: 'template_table_templatetable',
            path: '/template/table/templatetable',
            component: 'view.template_table_templatetable',
            meta: {
              title: 'template_table_templatetable'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'theme',
    path: '/theme',
    component: 'layout.base$view.theme',
    meta: {
      title: 'theme',
      icon: 'theme'
    }
  },
  {
    name: 'ucenter',
    path: '/ucenter',
    component: 'layout.base$view.ucenter',
    meta: {
      title: 'ucenter'
    }
  }
];
